import type { Metadata } from 'next'
import './globals.css'
import { getServerSession } from 'next-auth'
import SessionWrapper from './api/auth/[...nextauth]/SessionWrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface RootLayoutProps {
  children: React.ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession()
  return (
    <html lang="kr">
      <body>
        <SessionWrapper session={session}>{children}</SessionWrapper>
      </body>
    </html>
  )
}
